feat: add web ui
PKU-Alignment/align-anything pull request #3
Opened 2024-07-16 14:26 UTC by learnerljh

# Description

I developed a web UI for any-to-any model inference inspired by LLaVA.

## Motivation and Context

Why is this change required? What problem does it solve?
If it fixes an open issue, please link to the issue here.
You can use the syntax `close #1314520` if this solves the issue #15213
solved #2 
- [x] I have raised an issue to propose this change ([required](https://github.com/PKU-Alignment/align-anything/issues) for new features and bug fixes)

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [x] I have read the [CONTRIBUTION](https://github.com/PKU-Alignment/align-anything/blob/HEAD/.github/CONTRIBUTING.md) guide. (**required**)
- [x] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

2024-07-22 13:21 UTC, Gaiejj commented on pyproject.toml
> +    "PIL"
add `,`

2024-07-22 13:23 UTC, Gaiejj commented on align_anything/serve/controller.py
> +        # Dict[str -> WorkerInfo]
Can we remove this kind of annotation ?

2024-07-22 13:23 UTC, Gaiejj commented on align_anything/serve/controller.py
> +            # for chunk in response.iter_lines(decode_unicode=False, delimiter=b"\0"):
Please also remove this kind of annotation.

2024-07-22 13:24 UTC, Gaiejj commented on README.md
> +#### Launch a gradio web server.
Please remove `.`.

2024-07-22 13:26 UTC, learnerljh commented on README.md
> +#### Launch a gradio web server.
Thank you!

2024-07-22 13:26 UTC, Gaiejj requested changes
Mainly looks good to me, but some typos exist. Please fix them.

2024-07-22 14:12 UTC, Gaiejj approved these changes
LGTM.

2024-07-23 05:06 UTC, cby-pku approved these changes

2024-07-23 08:30 UTC, merged