Add Benchmarks and function for evaluation
PKU-Alignment/align-anything pull request #45
Opened 2024-08-15 07:05 UTC by Reindulger

## Description

- Add "Text+Image ➡️ Text" Benchmarks.
- Add function for models_pk of evaluation.
- Fix some bugs for evaluation and configs.

## Types of changes

What types of changes does your code introduce? Put an `x` in all the boxes that apply:

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds core functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Documentation (update in the documentation)

## Checklist

Go over all the following points, and put an `x` in all the boxes that apply.
If you are unsure about any of these, don't hesitate to ask. We are here to help!

- [ ] I have read the [[CONTRIBUTION](https://github.com/PKU-Alignment/align-anything/blob/HEAD/.github/CONTRIBUTING.md)](https://github.com/PKU-Alignment/align-anything/blob/HEAD/.github/CONTRIBUTING.md) guide. (**required**)
- [ ] My change requires a change to the documentation.
- [ ] I have updated the tests accordingly. (*required for a bug fix or a new feature*)
- [ ] I have updated the documentation accordingly.

2024-08-16 06:30 UTC, XuyaoWang approved these changes
LGTM.

2024-08-17 08:25 UTC, htlou approved these changes
LGTM, but I don't have time to look through all the details.

2024-08-17 08:48 UTC, Gaiejj commented on README_zh-CN.md
> +- `BENCHMARK`: 用于评估模型性能的一个或多个评估基准或数据集。例如，`("POPE" "MMBench")` 可用于在 POPE 和 MMBench 数据集上评估模型。列表中的每个基准将按顺序处理。
BENCHMARKS?

2024-08-17 08:52 UTC, Gaiejj commented on align_anything/configs/evaluation/benchmarks/pope.yaml
> +    max_new_tokens: 512
why we set them together?

2024-08-17 14:47 UTC, cby-pku requested changes
Wait for test.

2024-08-18 04:25 UTC, Reindulger commented on README_zh-CN.md
> +- `BENCHMARK`: 用于评估模型性能的一个或多个评估基准或数据集。例如，`("POPE" "MMBench")` 可用于在 POPE 和 MMBench 数据集上评估模型。列表中的每个基准将按顺序处理。
Yeah, so careless was I.

2024-08-18 04:26 UTC, Reindulger commented on align_anything/configs/evaluation/benchmarks/pope.yaml
> +    max_new_tokens: 512
Yeah, it's redundant. We will fix it.

2024-08-20 09:14 UTC, merged